- src/main/java/com/fauna/codec/json/PassThroughDeserializer.java
- src/main/java/com/fauna/codec/json/QueryTagsDeserializer.java
- src/main/java/com/fauna/response/wire/ConstraintFailureWire.java
- src/main/java/com/fauna/response/wire/ErrorInfoWire.java
- src/main/java/com/fauna/response/wire/QueryResponseWire.java
- src/test/java/com/fauna/codec/json/PassThroughDeserializerTest.java
- src/test/java/com/fauna/codec/json/QueryTagsDeserializerTest.java
* Add new models for to handle initial response deserialization
* Add QueryTags deserializer
* Add PassThrough deserializer (the JSON tree below the current node is returned as a raw json string)
BT-5043
* We want to simplify deserialization of the response
* We need to pass portions of the response through our own codecs
* Added unit tests
----
By submitting this pull request, I confirm that you can use, …
> New response models and custom deserializers

- src/main/java/com/fauna/codec/json/QueryTagsDeserializer.java
* Improve the query tags deserializer implementation
BT-5043
* PR feedback on https://github.com/fauna/fauna-jvm/pull/118
* Existing tests pass
----
> Use cleaner impl for query tags deser

- src/main/java/com/fauna/codec/codecs/PageCodec.java
- src/test/java/com/fauna/codec/codecs/PageCodecTest.java
* Add support for decoding arrays into pages
* Add support for decoding any potential singular type into a single-element page
BT-5070
The goal here is to reduce a possible sharp edge where a user decides to call client.paginate() with a query that doesn't return a Fauna Set type. Instead of failing, we'll decode arrays directly into pages as well as wrap whatever type they requested into a page if a single value is returned.
* Added unit tests
* - [ ] My change requires a change to the …
> Handle arrays and other types in page codec

- src/main/java/com/fauna/codec/DefaultCodecProvider.java
- src/main/java/com/fauna/codec/codecs/ClassCodec.java
- src/main/java/com/fauna/mapping/FieldInfo.java
- src/main/java/com/fauna/query/builder/Query.java
- src/test/java/com/fauna/beans/Circular.java
- src/test/java/com/fauna/codec/DefaultCodecProviderTest.java
- src/test/java/com/fauna/query/builder/QueryTest.java
* Make query extend QueryFragment so that it doesn't get wrapped in QueryVal during query building
* Register QueryValCodec
* Lazily get a codec from FieldInfo to allow for classes with circular references.
BT-5077
BT-5081
BT-5082
Some things weren't working
* Added/updated unit tests
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> QueryVal, Query Composition, and circular ref bug fixes

- src/main/java/com/fauna/codec/codecs/ClassCodec.java
- src/test/java/com/fauna/beans/ClassWithInheritance.java
- src/test/java/com/fauna/beans/ClassWithInheritanceL2.java
- src/test/java/com/fauna/codec/codecs/ClassCodecTest.java
* Obtain fields from all super classes in the ClassCodec
BT-5092
Class inheritance is not handled in the ClassCodec.
* Added unit test
----
> Handle super fields class codec

- src/main/java/com/fauna/codec/DefaultCodecProvider.java
- src/main/java/com/fauna/codec/codecs/EnumCodec.java
- src/test/java/com/fauna/codec/codecs/EnumCodecTest.java
Add an enum codec that encodes enums into a string and decodes them from a string. Strings must match the exact case of the enum value.
I opted for strings because strings carry information and aren't coupled to the order in which enum values are defined. I think end users will be happy that we don't store enums as ints in our database from this driver.
BT-5093
We can't encode or decode enums.
* Added a unit test
* - [ ] My change requires a change to the README, and I have updated it …
> Add support for encoding/decoding enums

- src/main/java/com/fauna/annotation/FaunaField.java
- src/main/java/com/fauna/annotation/FaunaFieldImpl.java
- src/main/java/com/fauna/codec/codecs/ClassCodec.java
- src/main/java/com/fauna/mapping/FieldInfo.java
- src/test/java/com/fauna/beans/ClassWithParameterizedFields.java
- src/test/java/com/fauna/codec/codecs/ClassCodecTest.java
- src/test/java/com/fauna/e2e/E2EQueryTest.java
* Remove genericTypeArgument from FaunaField
* Branch FieldInfo construction on whether Field.getGenericType() is a ParameterizedType or not
BT-5098
I realized while fixing some other things that I misunderstood an aspect of type erasure in Java and as a result built an overly complex annotation to deal with it.
Updated and extended tests
----
By submitting this pull request, I confirm that you can use, …
> Remove unnecessary genericTypeArg annotation field

- README.md
Super minor fix to consistently call this the 'JVM driver.'
> README: Consistently use 'JVM driver'

- README.md
Get the readme ready for a beta release
Because it has to be right! And good!
* - [x] New feature (non-breaking change that adds functionality)
----
> README: update define class content

- src/main/java/com/fauna/constants/ResponseFields.java
- src/main/java/com/fauna/exception/ServiceException.java
- src/main/java/com/fauna/response/ConstraintFailure.java
- src/main/java/com/fauna/response/ErrorInfo.java
- src/main/java/com/fauna/response/QueryFailure.java
- src/main/java/com/fauna/response/QueryResponse.java
- src/main/java/com/fauna/response/QueryResponseHandler.java
- src/main/java/com/fauna/response/StreamEvent.java
- src/main/java/com/fauna/response/wire/ConstraintFailureWire.java
- src/main/java/com/fauna/response/wire/ErrorInfoWire.java
- src/test/java/com/fauna/e2e/E2EConstraintTest.java
- src/test/java/com/fauna/e2e/E2EErrorHandlingTest.java
- src/test/java/com/fauna/e2e/E2EStreamingTest.java
- src/test/java/com/fauna/exception/ConstraintFailureTest.java
- src/test/java/com/fauna/exception/ErrorInfoTest.java
- src/test/java/com/fauna/exception/TestServiceException.java
This change is a step in the direction of getting rid of ObjectMapper so we can just directly use `JsonParser/UTF8FaunaParser` on the responses, so we never have to call `toString()`. In the long run this should be better, but this PR probably doesn't materially improve things from the users perspective.
I created task: https://faunadb.atlassian.net/browse/BT-5119 
We have what Lucas described as a 'Layer cake' in the response handling, and this goes part of the way to removing that.
Unit and E2E tests.
* - [ ] My change requires a change to Fauna …
> [Implement-error-parsers] Refactor to use JsonParser instead of ObjectMapper for parsing errors.

- src/main/java/com/fauna/client/FaunaClient.java
- src/main/java/com/fauna/client/FaunaConfig.java
- src/main/java/com/fauna/client/RequestBuilder.java
- src/main/java/com/fauna/response/QueryResponse.java
- src/test/java/com/fauna/client/FaunaClientTest.java
- src/test/java/com/fauna/client/RequestBuilderTest.java
- src/test/java/com/fauna/e2e/E2EQueryTest.java
Two key changes in here:
1. Allow max_contention_retries to be passed in via FaunaConfig, and set the required header when querying Fauna.
2. Update, and then pass back `last_txn_ts`.
For `max_contention_retries` I think one reason I hesitated to deal with it originally, is that I wasn't sure if it should get passed in via `QueryOptions` or `FaunaConfig`. I went with the latter because it seems more like a client-level value, but it could be changed.
These two headers are part of the Fauna API contract, so the driver needs to set them!
The tests `E2EQueryTest.clientTransactionTsOnSuccess|Failure` show that the returned client and Fauna API do what the code expects.= …
> [audit-todos] Address TODO by setting two headers

- src/main/java/com/fauna/client/FaunaClient.java
- src/main/java/com/fauna/client/PageIterator.java
- src/main/java/com/fauna/types/Page.java
- src/test/java/com/fauna/client/FaunaClientTest.java
- src/test/java/com/fauna/client/PageIteratorTest.java
- src/test/java/com/fauna/e2e/E2EPaginationTest.java
- src/test/java/com/fauna/types/PageTest.java
Address two pagination items that Lucas found in the bug bash.
* BT-5072 keeps pagination in-line with our other APIs where QueryOptions and the element type are optional parameters.
* BT-5073 (I think) addresses issues that developers of async apps, like restful servers might face.
Added some unit and E2E tests, I think all the code I touched is "covered".
----
By submitting this pull request, I confirm …
> [BT-5072-pagination-apis] Address BT-5072 and BT-5073

- src/main/java/com/fauna/client/FaunaClient.java
- src/main/java/com/fauna/client/PageIterator.java
- src/main/java/com/fauna/constants/ErrorMessages.java
- src/main/java/com/fauna/exception/ErrorHandler.java
- src/main/java/com/fauna/query/AfterToken.java
- src/main/java/com/fauna/types/Page.java
- src/test/java/com/fauna/e2e/E2EPaginationTest.java
I added two new methods to `FaunaClient` along with some refactoring of the error handling. Note that I did _not_ add the full complement of methods with/without `QueryOptions` and `elementClass` because I think there are already a lot of methods on `FaunaClient`.
Note that changing the signature of `Page.getAfter` from `Optional<String>` to `Optional<AfterToken>` is technically a breaking change, but I think this is OK since we are still in beta.
The feature request was driven by trying to implement a RESTful API in the sample app.
There was already a nice E2E test to modify, several unit tests check that we didn't accidentally change the exception handling.
* - [x] New feature (non-breaking change that adds functionality)
* - [x] …
> [BT-5120-pagination-ergonomics] Implement queryPage and asyncQueryPage APIs..

- README.md
With the upcoming release of Change Feeds, we're standardizing capitalization of "Event Streaming."
Also adds some links to the API reference to the Event Streaming section.
---
> [DOCS-3436] README: Fix 'Event Streaming' spelling

- src/main/java/com/fauna/client/FaunaConfig.java
- src/main/java/com/fauna/client/RequestBuilder.java
- src/main/java/com/fauna/stream/StreamRequest.java
- src/test/java/com/fauna/client/FaunaConfigTest.java
- src/test/java/com/fauna/client/RequestBuilderTest.java
- src/test/java/com/fauna/e2e/E2EQueryTest.java
- src/test/java/com/fauna/e2e/E2EStreamingTest.java
- src/test/java/com/fauna/stream/StreamRequestTest.java
I added support for setting the HttpClient timeout (HttpClient connect timeout, and Fauna query are already configurable).
I noticed this when testing logging support on Monday. It seems minor, but could also be frustrating for customers if we don't support it.
Unit and E2E tests.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> [BT-5174-http-timeout] Allow user-configurable HTTP timeout for query and stream requests.

- src/main/java/com/fauna/codec/UTF8FaunaParser.java
- src/test/java/com/fauna/codec/UTF8FaunaParserTest.java
* Add an internal token type for dealing with unmaterialized sets
* Handle start and end of unmaterialized set
BT-5261
Materialized and unmaterialized sets look slightly different on the wire. In the case of materialized sets, we encounter two end object json tokens that represent the end of the set. In the unmaterialized case, we only encounter one. When the reader encounters the unmaterialized set, it will cause the token stream to be shifted by one.
* Added unit test
* - [ ] My change …
> fix: handle unmaterialized sets

- concourse/pipeline.yml
Just a quick one: after merging my perf test PR, I noticed that the pipeline wasn't updating and it's because the whole pipeline is currently keying off of the `release` branch, so this change adds a new git resource for `main` that will trigger `set-self` and the perf tests, while the release job still runs out of the `release` branch.  There's a very slim possibility that a pipeline change in `main` that isn't cherry-picked to `release` could cause friction, but that seems highly unlikely and easy to catch in PR.
I want my perf tests to run!  👶 
It's Concourse, so YOLO.
* - [ ] My code follows the code …
> chore(pipeline): Run set-self and perf tests from main

- README.md
Updates the README's streaming section to use:
* New CDC terminology (`stream token` -> `event source`)
* New `eventSource()` and `eventsOn()` FQL methods
This aligns the README with the latest terminology in the docs and FQL.
N/A
* - [x] My change requires a change to Fauna documentation.
----
> [DOCS-3656] docs: Update CDC terminology

- src/main/java/com/fauna/client/BaseFaunaClient.java
- src/main/java/com/fauna/client/FaunaClient.java
- src/main/java/com/fauna/client/FaunaConfig.java
- src/main/java/com/fauna/client/FaunaStream.java
- src/main/java/com/fauna/client/ScopedFaunaClient.java
- src/main/java/com/fauna/client/StatsCollector.java
- src/main/java/com/fauna/client/StatsCollectorImpl.java
- src/main/java/com/fauna/response/QueryResponse.java
- src/test/java/com/fauna/client/FaunaClientTest.java
- src/test/java/com/fauna/client/FaunaConfigTest.java
- src/test/java/com/fauna/e2e/E2EPaginationTest.java
- src/test/java/com/fauna/e2e/E2EQueryTest.java
- src/test/java/com/fauna/e2e/E2EStreamingTest.java
- src/test/java/com/fauna/exception/ConstraintFailureTest.java
- src/test/java/com/fauna/exception/TestErrorHandler.java
- src/test/java/com/fauna/response/QueryResponseTest.java
* Use the stats collector from https://github.com/fauna/fauna-jvm/pull/159
* Collect stats on queries
* Collect stats on pagination (this happens through queries)
* Collect stats on stream events
BT-4971
* Some users want to track query stats (like read/write/compute ops) at the top level
* In the case of pagination, there's no way to track stats on the individual requests
* Integration tests for streams, pagination, and queries
* - [ ] My change requires a change to the README, and I have …
> Use stats collector

- .gitmodules
There's an auth issue when Concourse attempts to pull the `driver-perf-util` repo as a submodule via HTTP (no username), so I'm changing the `.gitmodules` file to use SSH.
I ran the following commands locally and they succeeded:
```
```
----
> chore(pipeline): Use SSH for perf-test git submodule

- build.gradle
* Add a build step that will bundle the jar with all dependencies. It will zip to `build/distributions/fauna-jvm-<version>.zip`
BT-4262
* For platform testing need to build the jar and bundle all of its dependencies to deploy to a cloud provider, such as AWS Lambda, for integration testing.
* I ran the build task locally and copied its output into our test app, then deployed it to AWS Lambda to verify it works. It does.
* - [ ] My change requires a change to the README, and I have updated …
> Add a build task to bundle the jar with deps

- src/main/java/com/fauna/client/FaunaClient.java
- src/main/java/com/fauna/client/PageIterator.java
- src/main/java/com/fauna/client/RequestBuilder.java
- src/main/java/com/fauna/event/FeedPage.java
- src/main/java/com/fauna/event/StreamOptions.java
- src/main/java/com/fauna/event/StreamRequest.java
- src/main/java/com/fauna/exception/ServiceException.java
- src/main/java/com/fauna/response/QueryFailure.java
- src/main/java/com/fauna/types/Page.java
- src/test/java/com/fauna/beans/InventorySource.java
- src/test/java/com/fauna/client/DefaultsTest.java
- src/test/java/com/fauna/client/FeedIteratorTest.java
- src/test/java/com/fauna/client/RequestBuilderTest.java
- src/test/java/com/fauna/e2e/E2EFeedsTest.java
- src/test/java/com/fauna/e2e/E2EStreamingTest.java
- src/test/java/com/fauna/stream/StreamRequestTest.java
1. User-facing Stream API now takes an `EventSource`, and `StreamOptions` instead of `StreamRequest`.
2. Replace usages of `toStream()` with `eventSource()`.
3. Add a new constructor to `PageIterator` that makes it possible to initialize with an existing page.
4. Ensure the `statsCollector` gets updated for feed page responses, (Leftover from PR #162)
Still TODO are README updates, final checks of test coverage, bug bash? etc.
It's worth aligning the user-facing APIs before we GA the driver.
The unit and integ tests are fairly comprehensive, I also discovered a few things while building a sample app (how to do deletes, and the PageIterator gap).
* - [ ] Breaking …
> [BT-5271-streams-api] Align the Streams API with Event Feeds terminology.

- src/main/java/com/fauna/client/QueryStatsSummary.java
- src/main/java/com/fauna/client/StatsCollectorImpl.java
- src/main/java/com/fauna/client/package-info.java
- src/main/java/com/fauna/response/QueryStats.java
- src/main/java/com/fauna/response/package-info.java
- src/test/java/com/fauna/exception/TestServiceException.java
- src/test/java/com/fauna/perf/PerformanceTest.java
* Modifies QueryStats and QueryStatsSummary to adhere to our checkstyle config.
* Adds a package-info.java for the two packages touched.
BT-5258
----
> Add javadocs for QueryStats

- src/main/java/com/fauna/response/ConstraintFailure.java
- src/main/java/com/fauna/response/ErrorInfo.java
- src/main/java/com/fauna/response/MultiByteBufferInputStream.java
- src/main/java/com/fauna/response/QueryFailure.java
- src/main/java/com/fauna/response/QueryResponse.java
- src/main/java/com/fauna/response/QueryStats.java
- src/main/java/com/fauna/response/QuerySuccess.java
* Apply entry rearrange to com.fauna.response.* classes
* Add javadocs to all com.fauna.response.* classes
* Apply non-formatting checkstyle fixes to all warnings in com.fauna.response.* classes
BT-5258
Consistency and documentation!
----
> Fix checkstyle and javadocs in com.fauna.response

- build.gradle
- concourse/pipeline.yml
Add pipeline configuration for AWS Lambda test.
Depends on: https://github.com/fauna/fauna-jvm/pull/172
Add 3rd party platform tests to ensure the driver works in the actual environment(s) where it might be run.
```
davidgriffin@Davids-MacBook-Pro-2 fauna-jvm % fly validate-pipeline --config concourse/pipeline.yml
looks good
davidgriffin@Davids-MacBook-Pro-2 fauna-jvm %
```
* - [x] New feature (non-breaking change that adds functionality)
----
By submitting this pull …
> [BT-4262-java-lambda] Add AWS Lambda tests to Pipeline.

- src/main/java/com/fauna/client/BaseFaunaClient.java
- src/main/java/com/fauna/client/ExponentialBackoffStrategy.java
- src/main/java/com/fauna/client/Fauna.java
- src/main/java/com/fauna/client/FaunaClient.java
- src/main/java/com/fauna/client/FaunaConfig.java
- src/main/java/com/fauna/client/FaunaRole.java
- src/main/java/com/fauna/client/FaunaScope.java
- src/main/java/com/fauna/client/Logging.java
- src/main/java/com/fauna/client/NoRetryStrategy.java
- src/main/java/com/fauna/client/PageIterator.java
- src/main/java/com/fauna/client/RequestBuilder.java
- src/main/java/com/fauna/client/RetryHandler.java
- src/main/java/com/fauna/client/ScopedFaunaClient.java
- src/main/java/com/fauna/client/StatsCollector.java
- src/main/java/com/fauna/client/StatsCollectorImpl.java
Add javadocs and fix other checkstyle issues in com.fauna.client
BT-5258
----
> Fix checkstyle issues in com.fauna.client

- src/main/java/com/fauna/codec/codecs/PageCodec.java
- src/test/java/com/fauna/codec/codecs/PageCodecTest.java
Handle unmaterialized sets in PageCodec.
BT-5310
We fixed this a while ago in the UTF8FaunaParser, but I forgot to include changes in the PageCodec as well.
Added a unit test.
----
> Handle unmaterialized sets in PageCodec

- README.md
Replaces the `EventSourceResponse` class with `EventSource` in the README. The`EventSourceResponse` class was removed with https://github.com/fauna/fauna-jvm/pull/184.
Keep the docs up-to-date.
N/A
----
> [DOCS-3726] Replace `EventSourceResponse` with `EventSource`

- concourse/pipeline.yml
The testtools image is not currently built in any of our Pipelines, so add it to the JVM driver Pipeline.
I added the JDK to the image so that we could run JVM / AWS Lambda platform test.
```
david@mac % fly validate-pipeline -c concourse/pipeline.yml
looks good
```
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [BT-4262-build-image] Build the testtools image in this Pipeline

- src/main/java/com/fauna/exception/NullDocumentException.java
Fixes a typo in the javadocs. I'll manually update the affected page once this is merged.
- Improve the docs.
- Stop a related javadoc warning
`./gradlew javadoc`
* - [x] My change requires a change to Fauna documentation.
----
> docs: Fix typo in javadocs

- concourse/pipeline.yml
- concourse/scripts/perf.sh
- src/test/java/com/fauna/e2e/E2EFeedsTest.java
- src/test/java/com/fauna/perf/PerformanceTest.java
This PR updates the perf tests with a few needed tweaks:
- Reduce frequency in the pipeline to 1/day
- Add a preliminary query in `BeforeAll` method to throw out initial connection
- Bring in latest `driver-perf-utils` commit and use CLI v3
Improving high percentile perf numbers
Cribbed from change that's live in `fauna-dotnet`
* - [x] Test only change
----
By submitting this pull request, I confirm that …
> chore(perf-tests): A few minor tweaks to perf tests
