README.md
src/main/java/com/fauna/client/FaunaClient.java
src/main/java/com/fauna/client/PageIterator.java
src/main/java/com/fauna/response/QueryResponse.java
src/main/java/com/fauna/serialization/PageDeserializer.java
src/main/resources/version.properties
src/test/java/com/fauna/client/PageIteratorTest.java
src/test/java/com/fauna/e2e/E2EPaginationTest.java
src/test/java/com/fauna/e2e/Fixtures.java
src/test/java/com/fauna/e2e/beans/Product.java

Implemented PageIterator. I attempted to follow the precedent of JS, Python, and DotNet drivers.
Pagination should work, also we told a customer it's coming.
There are currently E2E tests, but it could probably do with some unit tests, I can add them to this PR if we're not in a rush.
- x ] My code follows the code style of this project.
----

[BT-4261-pagination] Implement pagination via PageIterator (plus flatten() method).

---

.github/workflows/gradle-test.yml
build.gradle
src/main/java/com/fauna/response/ConstraintFailure.java

* Declare the sourcesJar task
* Make `sourcesJar` depend on `writeProps`
* Replace deprecated `outputFile` with `destinationFile`
* Add a step to run `gradle assemble` with PRs
Build is failing with:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':sourcesJar' (type 'Jar').
- Gradle detected a problem with the following location: '/tmp/build/5e2fb0c2/fauna-jvm-repository/src/main/resources'.
Reason: Task ':sourcesJar' uses this output of task ':writeProps' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':writeProps' as an input of ':sourcesJar'.
2. Declare an explicit dependency on …
```

Make sourcesJar depend on writeProps

---

.github/workflows/gradle-test.yml
build.gradle
src/main/java/com/fauna/response/ConstraintFailure.java

Lucas fixed a few things about the build in https://github.com/fauna/fauna-jvm/pull/104 and this PR merges them into the `release` branch.
Get the release out that we tried to get out yesterday.
Build succeeds!
----

[release-0.1.0-M4-fixed] Merge build fixes into release branch

---

src/main/java/com/fauna/codec/DefaultCodecRegistry.java
src/main/java/com/fauna/codec/codecs/DynamicCodec.java
src/main/java/com/fauna/codec/codecs/InstantCodec.java
src/main/java/com/fauna/codec/codecs/LocalDateCodec.java
src/main/java/com/fauna/codec/codecs/ModuleCodec.java
src/test/java/com/fauna/beans/ClassWithParameterizedFields.java
src/test/java/com/fauna/beans/ClassWithRefTagCollision.java
src/test/java/com/fauna/codec/codecs/CodecTests.java
src/test/java/com/fauna/codec/codecs/Fixtures.java
src/test/java/com/fauna/serialization/UTF8FaunaParserTest.java

* Add Module, Instant, and LocalDate codecs
* Remove unused code from DynamicCodec
* Add object equality assertion to roundtrip test
* Fix CharCodec test
* Next step on the codec story.
* Added/updated unit tests
----

Add Date, Time and Module codecs

---

README.md
src/main/java/com/fauna/annotation/FaunaFieldImpl.java
src/main/java/com/fauna/annotation/FaunaIgnore.java
src/main/java/com/fauna/annotation/FaunaObject.java
src/main/java/com/fauna/codec/codecs/ClassCodec.java
src/main/java/com/fauna/mapping/FieldInfo.java
src/main/java/com/fauna/mapping/MappingInfo.java
src/test/java/com/fauna/beans/ClassWithFaunaIgnore.java
src/test/java/com/fauna/beans/ClassWithFieldAttributeAndWithoutObjectAttribute.java
src/test/java/com/fauna/beans/ClassWithParameterizedFields.java
src/test/java/com/fauna/beans/ClassWithPropertyWithoutFieldAttribute.java
src/test/java/com/fauna/beans/ClassWithRefTagCollision.java
src/test/java/com/fauna/beans/PersonWithConflict.java
src/test/java/com/fauna/codec/codecs/CodecTests.java
src/test/java/com/fauna/codec/codecs/Fixtures.java
src/test/java/com/fauna/serialization/SerializerTest.java

* Add FaunaIgnore attribute to allow users to ignore properties
* Remove FaunaObject because we don't really need it right now
* The new class codec wasn't handling classes without attributes
* Simplify annotations:
* By default, encode all properties
* Allow users to override the name or declare a type arg for generics with FaunaField
* Allow users to ignore properties with FaunaIgnore
* Added/updated existing tests.
* - [X] Breaking change (backwards-incompatible fix or feature)
* - [ ] My change requires a change to the README, and I have updated it …

Add FaunaIgnore, remove FaunaObject

---

build.gradle
src/main/java/com/fauna/client/PageIterator.java
src/main/java/com/fauna/types/BaseDocument.java
src/main/java/com/fauna/types/NonNull.java
src/main/java/com/fauna/types/NullDoc.java
src/main/java/com/fauna/types/Page.java
src/test/java/com/fauna/client/FaunaClientTest.java
src/test/java/com/fauna/client/PageIteratorTest.java
src/test/java/com/fauna/e2e/E2EPaginationTest.java
src/test/java/com/fauna/e2e/E2EQueryTest.java
src/test/java/com/fauna/types/DocumentRefTest.java
src/test/java/com/fauna/types/DocumentTest.java
src/test/java/com/fauna/types/NamedDocumentRefTest.java
src/test/java/com/fauna/types/NamedDocumentTest.java
src/test/java/com/fauna/types/NonNullTest.java
src/test/java/com/fauna/types/NullDocTest.java
src/test/java/com/fauna/types/PageTest.java
src/test/java/com/fauna/types/TypeTestBase.java

* Update getters for public types to make them jackson-friendly
BT-5071
Some frameworks like SpringBoot allow you to return objects and handle JSON serialization under the hood. Presumably other frameworks will do the same, so let's make sure our objects follow common conventions to make them serializer friendly.
* Added unit tests for covered classes.
----
By submitting this pull request, I confirm that …

Make public types jackson friendly

---

README.md

Update readme to say beta instead of alpha
Preparation for release
----

Indicate beta in the driver readme

---

README.md

`getType()` can be important for streaming events. This adds an example use to the README.
----

[DOCS-3385] README: Add `getType()` ex for streaming

---

README.md
src/main/java/com/fauna/client/BaseFaunaClient.java
src/main/java/com/fauna/client/FaunaClient.java
src/main/java/com/fauna/client/FaunaConfig.java
src/main/java/com/fauna/client/Logging.java
src/main/java/com/fauna/client/RequestBuilder.java
src/main/java/com/fauna/client/RetryHandler.java
src/main/java/com/fauna/client/ScopedFaunaClient.java
src/main/java/com/fauna/codec/UTF8FaunaParser.java
src/test/java/com/fauna/client/FaunaConfigTest.java
src/test/java/com/fauna/client/RequestBuilderTest.java
src/test/java/com/fauna/client/TestRetryHandler.java
src/test/java/com/fauna/e2e/E2EErrorHandlingTest.java

Firstly I implemented request/response logging for the JVM driver. Secondly I think I fixed a bug where we were ignoring the `FAUNA_ENDPOINT` and `FAUNA_SECRET` environment variables.
The new debug facility can be enabled by setting `FAUNA_DEBUG=1` and disabled with `FAUNA_DEBUG=0` (or if the environment variable is missing). This will enable logging to `stderr` with `Leve.FINE` which is the equivalent of Log4j `DEBUG`. Users can also pass in their own log handler if they want to use a different log level, write to a file etc.
We recently had an event where a customer was receiving 401 Unauthorized responses from Fauna, and it was hard to tell why. If we had an easy way to see the headers they were sending on the client side, it would have been much easier to debug.
Other than running the …

[BT-5129-logging-tracing] Enable debug / tracing for the JVM driver.

---

.gitignore
.gitmodules
build.gradle
concourse/pipeline.yml
concourse/scripts/perf.sh
concourse/tasks/perf.yml
src/test/java/com/fauna/perf/MetricsHandler.java
src/test/java/com/fauna/perf/PerformanceTest.java
src/test/java/com/fauna/perf/TestTimings.java
src/test/java/com/fauna/perf/model/Manufacturer.java
src/test/java/com/fauna/perf/model/Product.java
src/test/java/com/fauna/perf/testdata/TestDataParser.java
src/test/java/com/fauna/perf/testdata/TestQueries.java
src/test/java/com/fauna/perf/testdata/TestQuery.java
src/test/java/com/fauna/perf/testdata/TestResponse.java

BT-5066
This PR adds performance tests that are very similar to the ones already added for `fauna-dotnet`; the tests consume a set of queries defined in the `fauna/driver-perf-utils` repo, runs them in a Concourse pipeline every 6h and outputs the statistics of the driver "overhead" to a private Slack channel.
These tests currently lack some parity with the .NET tests due to not having access to a stats collector on the client; once that's added, I can go back and improve the pagination tests.
I'll also be honest that I'm not a Java coder, so I warrant there may be some assumptions/approaches that could be improved - feel free to provide that feedback, but unless the errors are egregious, we should probably open a ticket and track fixing later.
See above
Plenty of local testing with …

feat(perf-tests): Add performance tests using common driver perf queries

---

.github/workflows/gradle-test.yml
README.md
src/main/java/com/fauna/client/BaseFaunaClient.java
src/main/java/com/fauna/client/FaunaClient.java
src/main/java/com/fauna/client/FeedIterator.java
src/main/java/com/fauna/client/RequestBuilder.java
src/main/java/com/fauna/client/ScopedFaunaClient.java
src/main/java/com/fauna/codec/DefaultCodecProvider.java
src/main/java/com/fauna/codec/codecs/DynamicCodec.java
src/main/java/com/fauna/codec/codecs/EventSourceResponseCodec.java
src/main/java/com/fauna/constants/ErrorMessages.java
src/main/java/com/fauna/constants/ResponseFields.java
src/main/java/com/fauna/exception/ErrorHandler.java
src/main/java/com/fauna/feed/EventSource.java
src/main/java/com/fauna/feed/FeedOptions.java
src/main/java/com/fauna/feed/FeedPage.java
src/main/java/com/fauna/feed/FeedRequest.java
src/main/java/com/fauna/feed/FeedSuccess.java
src/main/java/com/fauna/query/EventSourceResponse.java
src/main/java/com/fauna/query/QueryOptions.java
src/main/java/com/fauna/response/StreamEvent.java
src/main/java/com/fauna/stream/StreamRequest.java
src/test/java/com/fauna/client/DefaultsTest.java
src/test/java/com/fauna/client/FaunaClientTest.java
src/test/java/com/fauna/client/FeedIteratorTest.java
src/test/java/com/fauna/codec/codecs/DynamicCodecTest.java
src/test/java/com/fauna/e2e/E2EFeedsTest.java
src/test/java/com/fauna/e2e/E2EQueryTest.java
src/test/java/com/fauna/e2e/E2EStreamingTest.java
src/test/java/com/fauna/e2e/Fixtures.java

This change implements the new Event Feeds feature.
Event Feeds needs support in all drivers to be useful to customers.
Unit and E2E tests, I eyeballed the coverage and I think most of the new code is covered.
* - [x] New feature (non-breaking change that adds functionality)
----

[BT-5168-event-feeds] Implement Event Feeds for JVM

---

.github/workflows/gradle-test.yml
build.gradle
config/checkstyle/checkstyle.xml

- Add the default google checkstyle configuration
- Add checkstyle gradle config
- Run checkstyle as a PR check (warn only for now)
- We want consistent styling, and I like to default to things that are already out there.
----

Add checkstyle config

---

README.md

https://github.com/fauna/fauna-jvm/pull/154 included README docs, but there was some drift in the source code afterward. This catches up the README.
Ensure users have accurate docs.
Tested examples locally.
* - [x] My change requires a change to Fauna documentation.
----

README: Update Event Feeds info

---

README.md

Updates the README for changes in https://github.com/fauna/fauna-jvm/pull/164.
Ensures the docs are up-to-date and correct.
Tested examples locally
----

README: Update for Event Streams refactor

---

src/main/java/com/fauna/env/DriverEnvironment.java
src/main/java/com/fauna/env/package-info.java

* Fix checkstyle warnings in com.fauna.env
BT-5258
Consistency and documentation!
----

Fix checkstyle issues in com.fauna.env

---

concourse/pipeline.yml

Typo in URL means that Concourse can't find repo
Make the pipeline work!
Not tested.
----

Fix typo in GitHub URL.

---

src/main/java/com/fauna/event/EventSource.java
src/main/java/com/fauna/event/EventSourceResponse.java
src/main/java/com/fauna/event/FaunaEvent.java
src/main/java/com/fauna/event/FaunaStream.java
src/main/java/com/fauna/event/FeedIterator.java
src/main/java/com/fauna/event/FeedOptions.java
src/main/java/com/fauna/event/FeedPage.java
src/main/java/com/fauna/event/FeedRequest.java
src/main/java/com/fauna/event/StreamOptions.java
src/main/java/com/fauna/event/StreamRequest.java
src/main/java/com/fauna/event/package-info.java

* Fix checkstyle warnings in com.fauna.event
BT-5258
Consistency and documentation!
----

Fix checkstyle issues in com.fauna.event

---

README.md

Updates the README to remove references to the driver beta.
Prepare the README for GA release.
See [DOCS-3694](https://faunadb.atlassian.net/browse/DOCS-3694).
N/A
----
[DOCS-3694]: https://faunadb.atlassian.net/browse/DOCS-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

Update README for GA release

---

gradle.properties

We want to use semantic versioning so 1.0 -> 1.0.0
Be consistent with the other drivers.
n/a
----

Release 1.0.0

---

gradle.properties
src/test/java/com/fauna/configuration/VersionTest.java

Housekeeping after GA release this morning.
New builds should get a version other than 1.0.
Ran the tests locally.
----

[BT-5279-merge-back] Merge release back to main and update version to 1.0.1-SNAPSHOT

---

README.md

Updates the README to remove references to Event Feeds being in beta.
Prepare the README for GA release.
See [DOCS-4021](https://faunadb.atlassian.net/browse/DOCS-4021).
----
[DOCS-4021]: https://faunadb.atlassian.net/browse/DOCS-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

[DOCS-4021] docs: Update README for Event Feeds GA
